name: Ionic CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: LanguAI.Frontend

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: '20.19.0'

    - name: Install Dependencies
      run: npm i

    - name: Install ionic cli
      run: npm i -g @ionic/cli

    - name: Build
      run: npm run build-prod
